/* tslint:disable */
/* eslint-disable */
/**
 * auth__register
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AuthRegisterPost200Response
 */
export interface AuthRegisterPost200Response {
    /**
     * 
     * @type {boolean}
     * @memberof AuthRegisterPost200Response
     */
    mfaEnabled: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AuthRegisterPost200Response
     */
    active: boolean;
    /**
     * 
     * @type {string}
     * @memberof AuthRegisterPost200Response
     */
    secretImageUri: string;
}

/**
 * Check if a given object implements the AuthRegisterPost200Response interface.
 */
export function instanceOfAuthRegisterPost200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "mfaEnabled" in value;
    isInstance = isInstance && "active" in value;
    isInstance = isInstance && "secretImageUri" in value;

    return isInstance;
}

export function AuthRegisterPost200ResponseFromJSON(json: any): AuthRegisterPost200Response {
    return AuthRegisterPost200ResponseFromJSONTyped(json, false);
}

export function AuthRegisterPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AuthRegisterPost200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'mfaEnabled': json['mfaEnabled'],
        'active': json['active'],
        'secretImageUri': json['secretImageUri'],
    };
}

export function AuthRegisterPost200ResponseToJSON(value?: AuthRegisterPost200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'mfaEnabled': value.mfaEnabled,
        'active': value.active,
        'secretImageUri': value.secretImageUri,
    };
}

